services:
  animap:
    container_name: animap
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    environment:
      APP_ENV: "$APP_ENV"
      MAL_BASE_URL: "$MAL_BASE_URL"
      MAL_CLIENT_ID: "$MAL_CLIENT_ID"
      MAL_CLIENT_SECRET: "$MAL_CLIENT_SECRET"
      MAL_REDIRECT_URI: "$MAL_REDIRECT_URI"
    restart: unless-stopped

  animap-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: animap-tunnel
    environment:
      TUNNEL_TOKEN: "$TUNNEL_TOKEN"
    command: tunnel --no-autoupdate run
    depends_on:
      - animap
    restart: unless-stopped

volumes:
  caddy_data:
